// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lvMTIj0pIJsOYh-IP46P6ZDT7OCR89Y',
    appId: '1:340100178581:android:fa4c2800474fc0b35a719c',
    messagingSenderId: '340100178581',
    projectId: 'graduation-forbit',
    storageBucket: 'graduation-forbit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVDb2syjAl60JccPzUSBX2a6Anflb0NA',
    appId: '1:340100178581:ios:497dd4ef0a1799585a719c',
    messagingSenderId: '340100178581',
    projectId: 'graduation-forbit',
    storageBucket: 'graduation-forbit.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVDb2syjAl60JccPzUSBX2a6Anflb0NA',
    appId: '1:340100178581:ios:2aa346763cc398e85a719c',
    messagingSenderId: '340100178581',
    projectId: 'graduation-forbit',
    storageBucket: 'graduation-forbit.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
